#!/bin/bash


_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $LEGEND_REPO == "LEGENDBOT" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL0xFR0VORC1PUy9MRUdFTkRVU0VSQk9UL2FyY2hpdmUvbWFzdGVyLnppcA==" | base64 -d
    elif [[ $LEGEND_REPO == "LEGENDBOT" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL0xFR0VORC1PUy9MRUdFTkRVU0VSQk9UL2FyY2hpdmUvbWFzdGVyLnppcA==" | base64 -d
    elif [[ $LEGEND_REPO =~ $regex ]]
    then
        if [[ $LEGEND_REPO_BRANCH ]]
        then
            echo "${LEGEND_REPO}/archive/${LEGEND_REPO_BRANCH}.zip"
        else
            echo "${LEGEND_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL0xFR0VORC1PUy9MRUdFTkRVU0VSQk9UL2FyY2hpdmUvbWFzdGVyLnppcA==" | base64 -d
    fi
}


_set_bot () {
    local zippath
    zippath="LEGENDBOT.zip"
    echo "  Downloading LegendBot V2.O Source Code..."
    wget -q $(_get_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    LEGENDPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    echo "  LegendBot V2.O Cleaning.."
    rm -rf "$zippath"
    sleep 5
    cd $LEGENDPATH
    echo "    ⚜️ѕταяτιиg ѕмοοτнєѕτ 𝕷𝐞̂𝐠𝐞́𝐧̃𝐝𝕭ø𝖙 V2.O⚜️     "
    echo "
    LEGENDBOT
    "

    python3 ../superspeedo/superupdater.py ../legendrequirements.txt legendrequirements.txt
    python3 -m superos
}

_set_bot
